from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from pyqtgraph import ImageView


class Ui_MainWindow(object):
    """
    Ekranda gözüken nesnelerin oluşturulduğu fonksiyon.
    İçerisinde ekranda yer alan bütün nesneler yer almaktadır. Önreğin Groupbox, Listbox, TextBox, Label ve Butonlar
    """
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1458, 911)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 10, 461, 731))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        # sol kısımda yer alan hesaplama ekranının yer aldığı GroupBox.
        self.groupBox = QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setStyleSheet(u"background-color: rgb(106, 255, 243);")
        # ÜRÜN yazan label
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 71, 21))
        font = QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)
        # BİRİM FİYATI yazan label
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(90, 30, 181, 21))
        self.label_2.setFont(font)
        self.label_2.setAlignment(Qt.AlignCenter)
        # ADET yazan label
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(280, 30, 71, 21))
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignCenter)
        # TUTAR yazan label
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(370, 30, 81, 20))
        self.label_4.setFont(font)
        self.label_4.setAlignment(Qt.AlignCenter)
        # Yayla Çorbası yazan label
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 80, 111, 16))
        # Mercimek Çorbası yazan label
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 110, 131, 16))
        # Kelle Paça Çorbası yazan label
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 140, 141, 16))
        # Ezogelin Çorbası yazan label
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 170, 131, 16))
        # 60₺ yazan label
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(160, 80, 31, 16))
        self.label_10 = QLabel(self.groupBox)
        # 50₺ yazan label
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(160, 110, 61, 16))
        self.label_11 = QLabel(self.groupBox)
        # 70₺ yazan label
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(160, 140, 41, 16))
        self.label_12 = QLabel(self.groupBox)
        # 50₺ yazan label
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(160, 170, 41, 16))
        # Yayla Çorbası Edit
        self.lineEdit = QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(280, 80, 61, 22))
        self.lineEdit.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # Mercimek Çorbası Edit
        self.lineEdit_1 = QLineEdit(self.groupBox)
        self.lineEdit_1.setObjectName(u"lineEdit_1")
        self.lineEdit_1.setGeometry(QRect(280, 110, 61, 22))
        self.lineEdit_1.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # Kelle Paça Çorbası Edit
        self.lineEdit_2 = QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(280, 140, 61, 22))
        self.lineEdit_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # Ezogelin Çorbası Edit
        self.lineEdit_3 = QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(280, 170, 61, 22))
        self.lineEdit_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # Hesapla butonu
        self.pushButton = QPushButton(self.groupBox)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(370, 600, 75, 24))

        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(176, 241, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(121, 225, 247, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(33, 104, 120, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(44, 139, 160, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        brush6 = QBrush(QColor(161, 232, 247, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush6)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        brush8 = QBrush(QColor(67, 209, 240, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        self.pushButton.setPalette(palette)
        self.pushButton.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # Sonuçların yazdığı label0
        self.result = QLabel(self.groupBox)
        self.result.setObjectName(u"result")
        self.result.setGeometry(QRect(360, 80, 41, 20))
        self.result.setAlignment(Qt.AlignCenter)
        self.verticalLayoutWidget_2 = QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(0, 630, 461, 121))

        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        # Seçili Masa yaza yazan groupbox
        self.groupBox_2 = QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # Masa isminin yazdığı groupbox
        self.label_17 = QLabel(self.groupBox_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(150, 30, 161, 51))
        font1 = QFont()
        font1.setPointSize(25)
        self.label_17.setFont(font1)
        self.label_17.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.label_17.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.groupBox_2)
        # Sonuçların yazdığı label1
        self.result_1 = QLabel(self.groupBox)
        self.result_1.setObjectName(u"result_1")
        self.result_1.setGeometry(QRect(360, 110, 41, 20))
        self.result_1.setAlignment(Qt.AlignCenter)
        # Sonuçların yazdığı label2
        self.result_2 = QLabel(self.groupBox)
        self.result_2.setObjectName(u"result_2")
        self.result_2.setGeometry(QRect(360, 140, 41, 20))
        self.result_2.setAlignment(Qt.AlignCenter)
        # Sonuçların yazdığı label3
        self.result_3 = QLabel(self.groupBox)
        self.result_3.setObjectName(u"result_3")
        self.result_3.setGeometry(QRect(360, 170, 41, 20))
        self.result_3.setAlignment(Qt.AlignCenter)
        # Sonuçların yazdığı label4
        self.label_21 = QLabel(self.groupBox)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(310, 560, 141, 31))
        self.label_21.setAlignment(Qt.AlignCenter)
        # Sonuçların yazdığı label6
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(140, 60, 81, 16))
        font2 = QFont()
        font2.setPointSize(12)
        self.label_13.setFont(font2)
        # Kuru Fasulye Edit
        self.lineEdit_4 = QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(280, 230, 61, 22))
        self.lineEdit_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # Kurufasülye label
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 230, 111, 16))
        # 80 yazan label
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(160, 260, 51, 16))
        # Tas Kebabı yazan label
        self.label_22 = QLabel(self.groupBox)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 320, 101, 16))
        # Karınıyarık Edit
        self.lineEdit_5 = QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(280, 260, 61, 22))
        self.lineEdit_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # Karnıyarık yazan label
        self.label_23 = QLabel(self.groupBox)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 260, 111, 16))
        # 90 yazan label
        self.label_24 = QLabel(self.groupBox)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(160, 320, 41, 16))
        # Sonuçların yazdığı label5
        self.result_5 = QLabel(self.groupBox)
        self.result_5.setObjectName(u"result_5")
        self.result_5.setGeometry(QRect(360, 260, 41, 20))
        self.result_5.setAlignment(Qt.AlignCenter)
        # İzmir Köfte Edit
        self.lineEdit_6 = QLineEdit(self.groupBox)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(280, 290, 61, 22))
        self.lineEdit_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # Sonuçların yazdığı label4
        self.result_4 = QLabel(self.groupBox)
        self.result_4.setObjectName(u"result_4")
        self.result_4.setGeometry(QRect(360, 230, 41, 20))
        self.result_4.setAlignment(Qt.AlignCenter)
        # Sonuçların yazdığı label7
        self.result_7 = QLabel(self.groupBox)
        self.result_7.setObjectName(u"result_7")
        self.result_7.setGeometry(QRect(360, 320, 41, 20))
        self.result_7.setAlignment(Qt.AlignCenter)
        # 70 yazan label
        self.label_28 = QLabel(self.groupBox)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(160, 290, 51, 16))
        # Tas Kebabı Edit
        self.lineEdit_7 = QLineEdit(self.groupBox)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(280, 320, 61, 22))
        self.lineEdit_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # 60 yazan label
        self.label_29 = QLabel(self.groupBox)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(160, 230, 51, 16))
        # Sonuçların yazdığı label6
        self.result_6 = QLabel(self.groupBox)
        self.result_6.setObjectName(u"result_6")
        self.result_6.setGeometry(QRect(360, 290, 41, 20))
        self.result_6.setAlignment(Qt.AlignCenter)
        # İzmir Köfte yazan label
        self.label_31 = QLabel(self.groupBox)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 290, 111, 16))
        # Ana Yemekler Yazan label
        self.label_32 = QLabel(self.groupBox)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(110, 200, 131, 20))
        self.label_32.setFont(font2)
        # 40 yazan label
        self.label_34 = QLabel(self.groupBox)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(160, 410, 51, 16))
        # Sonuçların yazdığı label8
        self.result_8 = QLabel(self.groupBox)
        self.result_8.setObjectName(u"result_8")
        self.result_8.setGeometry(QRect(360, 380, 41, 20))
        self.result_8.setAlignment(Qt.AlignCenter)
        # Baklava yazan label
        self.label_38 = QLabel(self.groupBox)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 380, 81, 16))
        # Sütlaç yazan label
        self.label_39 = QLabel(self.groupBox)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 410, 111, 16))
        # Baklava Edit
        self.lineEdit_9 = QLineEdit(self.groupBox)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(280, 410, 61, 22))
        self.lineEdit_9.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # Tatlılar yazan label
        self.label_41 = QLabel(self.groupBox)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(140, 350, 111, 16))
        self.label_41.setFont(font2)
        # 120 yazan label
        self.label_42 = QLabel(self.groupBox)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(160, 380, 51, 16))
        # Sütlaç Edit
        self.lineEdit_8 = QLineEdit(self.groupBox)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(280, 380, 61, 22))
        self.lineEdit_8.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # Sonuçların yazdığı label9
        self.result_9 = QLabel(self.groupBox)
        self.result_9.setObjectName(u"result_9")
        self.result_9.setGeometry(QRect(360, 410, 41, 20))
        self.result_9.setAlignment(Qt.AlignCenter)
        # Kola Edit
        self.lineEdit_10 = QLineEdit(self.groupBox)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(280, 470, 61, 22))
        self.lineEdit_10.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # 15 yazan label
        self.label_35 = QLabel(self.groupBox)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(160, 500, 41, 16))
        # Ayran yazan label
        self.label_40 = QLabel(self.groupBox)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 500, 111, 21))
        # İçecekler yazan label
        self.label_43 = QLabel(self.groupBox)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(140, 435, 111, 21))
        self.label_43.setFont(font2)
        # Sonuçların yazdığı label11
        self.result_11 = QLabel(self.groupBox)
        self.result_11.setObjectName(u"result_11")
        self.result_11.setGeometry(QRect(360, 500, 41, 20))
        self.result_11.setAlignment(Qt.AlignCenter)
        self.result_10 = QLabel(self.groupBox)
        # Sonuçların yazdığı label10
        self.result_10.setObjectName(u"result_10")
        self.result_10.setGeometry(QRect(360, 470, 41, 20))
        self.result_10.setAlignment(Qt.AlignCenter)
        # Ayran Edit
        self.lineEdit_11 = QLineEdit(self.groupBox)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(280, 500, 61, 22))
        self.lineEdit_11.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        # 20 yazan label
        self.label_47 = QLabel(self.groupBox)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(160, 470, 41, 16))
        # Kola yazan label
        self.label_48 = QLabel(self.groupBox)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(10, 470, 81, 16))
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.lineEdit.raise_()
        self.lineEdit_1.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.pushButton.raise_()
        self.result.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.result_1.raise_()
        self.result_2.raise_()
        self.result_3.raise_()
        self.label_21.raise_()
        self.label_13.raise_()
        self.lineEdit_4.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_22.raise_()
        self.lineEdit_5.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.result_5.raise_()
        self.lineEdit_6.raise_()
        self.result_4.raise_()
        self.result_7.raise_()
        self.label_28.raise_()
        self.lineEdit_7.raise_()
        self.label_29.raise_()
        self.result_6.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.label_34.raise_()
        self.result_8.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.lineEdit_9.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.lineEdit_8.raise_()
        self.result_9.raise_()
        self.lineEdit_10.raise_()
        self.label_35.raise_()
        self.label_40.raise_()
        self.label_43.raise_()
        self.result_11.raise_()
        self.result_10.raise_()
        self.lineEdit_11.raise_()
        self.label_47.raise_()
        self.label_48.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()

        self.verticalLayout.addWidget(self.groupBox)


        self.horizontalLayout.addLayout(self.verticalLayout)

        self.horizontalLayoutWidget_3 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(490, 10, 661, 811))

        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        # Yemek algılama ekranının yer aldığı groupbox
        self.groupBox_3 = QGroupBox(self.horizontalLayoutWidget_3)
        self.groupBox_3.setObjectName(u"groupBox_3")
        # Algılanan nesneler groupbox
        self.groupBox_5 = QGroupBox(self.groupBox_3)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(0, 510, 661, 301))
        # Algılanan yemeklerin eklendiği liste kutusu
        self.listWidget = QListWidget(self.groupBox_5)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(10, 20, 641, 201))
        # İşlem butonları groupbox
        self.groupBox_6 = QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(470, 230, 181, 71))
        # Temizle butonu
        self.pushButton_3 = QPushButton(self.groupBox_6)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(20, 30, 75, 24))
        # Gönder butonu
        self.pushButton_2 = QPushButton(self.groupBox_6)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(100, 30, 75, 24))
        # Görünün yer aldığı pencere
        self.ImageView = ImageView(self.groupBox_3)
        self.ImageView.setObjectName(u"ImageView")
        self.ImageView.setGeometry(QRect(0, 20, 661, 480))

        self.horizontalLayout_3.addWidget(self.groupBox_3)

        self.horizontalLayoutWidget_4 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(1170, 10, 231, 621))
        self.horizontalLayout_4 = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        # Masa isimlerinin yer aldığı groupbox
        self.groupBox_4 = QGroupBox(self.horizontalLayoutWidget_4)
        self.groupBox_4.setObjectName(u"groupBox_4")
        # Masa 10 butonu
        self.masa10 = QPushButton(self.groupBox_4)
        self.masa10.setObjectName(u"masa10")
        self.masa10.setGeometry(QRect(20, 570, 81, 41))
        # Masa 14 butonu
        self.masa14 = QPushButton(self.groupBox_4)
        self.masa14.setObjectName(u"masa14")
        self.masa14.setGeometry(QRect(130, 210, 81, 41))
        # Masa 15 butonu
        self.masa15 = QPushButton(self.groupBox_4)
        self.masa15.setObjectName(u"masa15")
        self.masa15.setGeometry(QRect(130, 270, 81, 41))
        # Masa 6 butonu
        self.masa6 = QPushButton(self.groupBox_4)
        self.masa6.setObjectName(u"masa6")
        self.masa6.setGeometry(QRect(20, 330, 81, 41))
        # Masa 1 butonu
        self.masa1 = QPushButton(self.groupBox_4)
        self.masa1.setObjectName(u"masa1")
        self.masa1.setGeometry(QRect(20, 30, 81, 41))
        # Masa 19 butonu
        self.masa19 = QPushButton(self.groupBox_4)
        self.masa19.setObjectName(u"masa19")
        self.masa19.setGeometry(QRect(130, 510, 81, 41))
        # Masa 7 butonu
        self.masa7 = QPushButton(self.groupBox_4)
        self.masa7.setObjectName(u"masa7")
        self.masa7.setGeometry(QRect(20, 390, 81, 41))
        # Masa 8 butonu
        self.masa8 = QPushButton(self.groupBox_4)
        self.masa8.setObjectName(u"masa8")
        self.masa8.setGeometry(QRect(20, 450, 81, 41))
        # Masa 16 butonu
        self.masa16 = QPushButton(self.groupBox_4)
        self.masa16.setObjectName(u"masa16")
        self.masa16.setGeometry(QRect(130, 330, 81, 41))
        # Masa 4 butonu
        self.masa4 = QPushButton(self.groupBox_4)
        self.masa4.setObjectName(u"masa4")
        self.masa4.setGeometry(QRect(20, 210, 81, 41))
        # Masa 13 butonu
        self.masa13 = QPushButton(self.groupBox_4)
        self.masa13.setObjectName(u"masa13")
        self.masa13.setGeometry(QRect(130, 150, 81, 41))
        # Masa 20 butonu
        self.masa20 = QPushButton(self.groupBox_4)
        self.masa20.setObjectName(u"masa20")
        self.masa20.setGeometry(QRect(130, 570, 81, 41))
        # Masa 3 butonu
        self.masa3 = QPushButton(self.groupBox_4)
        self.masa3.setObjectName(u"masa3")
        self.masa3.setGeometry(QRect(20, 150, 81, 41))
        # Masa 17 butonu
        self.masa17 = QPushButton(self.groupBox_4)
        self.masa17.setObjectName(u"masa17")
        self.masa17.setGeometry(QRect(130, 390, 81, 41))
        # Masa 9 butonu
        self.masa9 = QPushButton(self.groupBox_4)
        self.masa9.setObjectName(u"masa9")
        self.masa9.setEnabled(True)
        self.masa9.setGeometry(QRect(20, 510, 81, 41))
        # Masa 2 butonu
        self.masa2 = QPushButton(self.groupBox_4)
        self.masa2.setObjectName(u"masa2")
        self.masa2.setGeometry(QRect(20, 90, 81, 41))
        # Masa 12 butonu
        self.masa12 = QPushButton(self.groupBox_4)
        self.masa12.setObjectName(u"masa12")
        self.masa12.setGeometry(QRect(130, 90, 81, 41))
        # Masa 5 butonu
        self.masa5 = QPushButton(self.groupBox_4)
        self.masa5.setObjectName(u"masa5")
        self.masa5.setGeometry(QRect(20, 270, 81, 41))
        # Masa 18 butonu
        self.masa18 = QPushButton(self.groupBox_4)
        self.masa18.setObjectName(u"masa18")
        self.masa18.setGeometry(QRect(130, 450, 81, 41))
        # Masa 11 butonu
        self.masa11 = QPushButton(self.groupBox_4)
        self.masa11.setObjectName(u"masa11")
        self.masa11.setGeometry(QRect(130, 30, 81, 41))

        self.horizontalLayout_4.addWidget(self.groupBox_4)
        # Logunun yer aldığı groupbox
        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 750, 461, 111))
        # Logonun yer aldığı label
        self.label_16 = QLabel(self.groupBox_7)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 0, 461, 100))
        self.label_16.setPixmap(QPixmap(u"logo.png"))
        self.label_16.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1458, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi
    """Yukarıda yer alan nesnelerin isimlerinin ve belli özelliklerinin belirlendiği fonksiyon"""
    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Hesaplama Ekran\u0131", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u00dcR\u00dcN", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"B\u0130R\u0130M F\u0130YATI", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"ADET", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"TUTAR", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Yayla \u00c7orbas\u0131", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Mercimek \u00c7orbas\u0131", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Kelle Pa\u00e7a \u00c7orbas\u0131", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Ezogelin \u00c7orbas\u0131", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"60\u20ba", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"50\u20ba", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"70\u20ba", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"50\u20ba", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"HESAPLA", None))
        self.result.setText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Se\u00e7ili Masa", None))
        self.label_17.setText("")
        self.result_1.setText("")
        self.result_2.setText("")
        self.result_3.setText("")
        self.label_21.setText("")
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u00c7orbalar", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Kuru Fas\u00fclye", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"80\u20ba", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Tas Kebab\u0131", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Karn\u0131yar\u0131k", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"90\u20ba", None))
        self.result_5.setText("")
        self.result_4.setText("")
        self.result_7.setText("")
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"70\u20ba", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"60\u20ba", None))
        self.result_6.setText("")
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"\u0130zmir K\u00f6fte", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Ana Yemekler", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"40\u20ba", None))
        self.result_8.setText("")
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Baklava", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"S\u00fctla\u00e7", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"Tatl\u0131lar", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"120\u20ba", None))
        self.result_9.setText("")
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"15\u20ba", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Ayran", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"\u0130\u00e7ecekler", None))
        self.result_11.setText("")
        self.result_10.setText("")
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"20\u20ba", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Kola", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Yemek Alg\u0131lama Ekran\u0131", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Alg\u0131lanan Nesneler", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"\u0130\u015flem Butonlar\u0131", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Temizle", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"G\u00f6nder", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Masa Adlar\u0131", None))
        self.masa10.setText(QCoreApplication.translate("MainWindow", u"Masa 10", None))
        self.masa14.setText(QCoreApplication.translate("MainWindow", u"Masa 14", None))
        self.masa15.setText(QCoreApplication.translate("MainWindow", u"Masa 15", None))
        self.masa6.setText(QCoreApplication.translate("MainWindow", u"Masa 6", None))
        self.masa1.setText(QCoreApplication.translate("MainWindow", u"Masa 1", None))
        self.masa19.setText(QCoreApplication.translate("MainWindow", u"Masa 19", None))
        self.masa7.setText(QCoreApplication.translate("MainWindow", u"Masa 7", None))
        self.masa8.setText(QCoreApplication.translate("MainWindow", u"Masa 8", None))
        self.masa16.setText(QCoreApplication.translate("MainWindow", u"Masa 16", None))
        self.masa4.setText(QCoreApplication.translate("MainWindow", u"Masa 4", None))
        self.masa13.setText(QCoreApplication.translate("MainWindow", u"Masa 13", None))
        self.masa20.setText(QCoreApplication.translate("MainWindow", u"Masa 20", None))
        self.masa3.setText(QCoreApplication.translate("MainWindow", u"Masa 3", None))
        self.masa17.setText(QCoreApplication.translate("MainWindow", u"Masa 17", None))
        self.masa9.setText(QCoreApplication.translate("MainWindow", u"Masa 9", None))
        self.masa2.setText(QCoreApplication.translate("MainWindow", u"Masa 2", None))
        self.masa12.setText(QCoreApplication.translate("MainWindow", u"Masa 12", None))
        self.masa5.setText(QCoreApplication.translate("MainWindow", u"Masa 5", None))
        self.masa18.setText(QCoreApplication.translate("MainWindow", u"Masa 18", None))
        self.masa11.setText(QCoreApplication.translate("MainWindow", u"Masa 11", None))
        self.groupBox_7.setTitle("")
        self.label_16.setText("")
    # retranslateUi

